services:
  playwright-sse-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - mcp-network
    container_name: playwright-sse-mcp-server
    environment:
      - NODE_ENV=production

networks:
  mcp-network:
    external: true
