services:
  playwright-sse-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY:-no}
    ports:
      - "${PORT:-3002}:${PORT:-3002}"
    networks:
      - mcp-network
    container_name: playwright-sse-mcp-server
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3002}

networks:
  mcp-network:
    external: true
